# Generated by Django 5.1.5 on 2025-01-22 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0003_comment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="created_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
